[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "hg"
version = "2023.12.12"
dependencies = [
#    "pytest>=7.4.3",
    "frozendict>=2.3.10",
    "more-itertools>=10.1.0",
    "sortedcontainers>=2.4.0",
]
requires-python = ">=3.11"
authors = [
  {name = "Howard Henson", email = "howard@henson.me.uk"},
]
maintainers = [
]
description = "A functional reactive engine"
readme = "README.md"
license = {file = "LICENSE"}
keywords = [
    "reactive", "graph", "fpg", "forward propogating graph", "time series", "functional reactive programming",
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python"
]

[tool.pytest.ini_options]
minversion = "7.4.3"
addopts = "-ra -q"
testpaths = [
    "test",
]

[project.urls]
Homepage = "https://github.com/hhenson/hg"
Repository = "https://github.com/hhenson/hg.git"
